# Generated by Django 3.2.25 on 2024-05-02 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=10)),
                ('speciality', models.CharField(max_length=50)),
                ('day_available', models.CharField(max_length=50)),
                ('timings_available', models.CharField(max_length=50)),
                ('avilable_date', models.DateField()),
                ('doctor_status', models.CharField(default='pending', help_text='doctor_status', max_length=50, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doctor_image', models.ImageField(upload_to='doctor/images')),
            ],
            options={
                'db_table': 'doctors_details',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.CharField(max_length=100, null=True)),
                ('Review', models.CharField(max_length=225, null=True)),
                ('Sentiment', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('Reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.patientmodel')),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
    ]
