# Generated by Django 3.2.25 on 2024-05-02 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicModel',
            fields=[
                ('clinic_id', models.AutoField(primary_key=True, serialize=False)),
                ('clinic_name', models.CharField(max_length=100)),
                ('clinic_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('diagnostic_center', 'Diagnostic Center')], max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('clinic_password', models.CharField(max_length=100, null=True)),
                ('clinic_city', models.TextField(null=True)),
                ('address', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('clinic_status', models.CharField(default='pending', help_text='clinic_status', max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='images/')),
                ('license', models.FileField(upload_to='media/')),
            ],
            options={
                'db_table': 'clinic_details',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_file', models.FileField(blank=True, null=True, unique=True, upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.patientmodel')),
            ],
            options={
                'db_table': 'prescription_details',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('dentist', 'Dentist'), ('doctor', 'Doctor'), ('physical-therapy', 'Physical Therapy')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('clinic', models.CharField(choices=[('in-clinic', 'In-clinic'), ('virtual', 'Virtual')], max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment_status', models.CharField(default='pending', help_text='Appointment status', max_length=50, null=True)),
                ('appointed_doctor', models.CharField(max_length=20, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.patientmodel')),
            ],
            options={
                'db_table': 'appointment_details',
            },
        ),
    ]
